const countries = [
  "India",
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Austria",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Ireland",
  "Portugal",
  "Greece",
  "Poland",
  "Czech Republic",
  "Hungary",
  "Romania",
  "Bulgaria",
  "Croatia",
  "Serbia",
  "Slovakia",
  "Slovenia",
  "Ukraine",
  "Russia",
  "Turkey",
  "Japan",
  "China",
  "South Korea",
  "North Korea",
  "Thailand",
  "Singapore",
  "Malaysia",
  "Indonesia",
  "Philippines",
  "Vietnam",
  "Cambodia",
  "Laos",
  "Myanmar",
  "Nepal",
  "Bhutan",
  "Bangladesh",
  "Sri Lanka",
  "Pakistan",
  "Afghanistan",
  "Iran",
  "Iraq",
  "Saudi Arabia",
  "United Arab Emirates",
  "Qatar",
  "Kuwait",
  "Oman",
  "Bahrain",
  "Yemen",
  "Israel",
  "Jordan",
  "Lebanon",
  "Syria",
  "Egypt",
  "Libya",
  "Tunisia",
  "Algeria",
  "Morocco",
  "South Africa",
  "Nigeria",
  "Kenya",
  "Ethiopia",
  "Ghana",
  "Uganda",
  "Tanzania",
  "Zimbabwe",
  "Zambia",
  "Botswana",
  "Namibia",
  "Mozambique",
  "Angola",
  "Cameroon",
  "Sudan",
  "Argentina",
  "Brazil",
  "Chile",
  "Colombia",
  "Peru",
  "Venezuela",
  "Uruguay",
  "Paraguay",
  "Bolivia",
  "Ecuador",
  "Mexico",
  "Cuba",
  "Dominican Republic",
  "Jamaica",
  "Costa Rica",
  "Panama",
  "Guatemala",
  "Honduras",
  "El Salvador",
  "Nicaragua",
  "New Zealand",
];

const countryCities = {
  India: [
    "Mumbai",
    "Delhi",
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Kolkata",
    "Pune",
    "Ahmedabad",
    "Jaipur",
    "Lucknow",
    "Ranchi",
    "Kanpur",
    "Nagpur",
    "Indore",
    "Thane",
    "Jamshedpur",
    "Visakhapatnam",
    "Agra",
    "Nashik",
    "Faridabad",
    "Bhubaneswar",
    "Amritsar",
    "Allahabad",
    "Vijayawada",
    "Patna",
    "Muzzafarpur",
    "Durgapur",
    "Asansol",
    "Navi Mumbai",
    "Meerut",
    "Kerala",
    "Gurgaon",
    "North Goa",
    "South Goa",
    "Bokaro",
    "Hazaribagh",
    "Dhanbad",
    "Rourkela",
    "Dumka",
  ],
  "United States": [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "San Francisco",
    "Miami",
  ],
  "United Kingdom": [
    "London",
    "Manchester",
    "Birmingham",
    "Liverpool",
    "Leeds",
    "Glasgow",
  ],
  Canada: ["Toronto", "Vancouver", "Montreal", "Ottawa", "Calgary", "Edmonton"],
  Australia: [
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adelaide",
    "Canberra",
  ],
  Germany: ["Berlin", "Munich", "Hamburg", "Frankfurt", "Cologne", "Stuttgart"],
  France: ["Paris", "Lyon", "Marseille", "Nice", "Toulouse", "Bordeaux"],
  Italy: ["Rome", "Milan", "Venice", "Florence", "Naples", "Turin"],
  Spain: ["Madrid", "Barcelona", "Valencia", "Seville", "Malaga", "Bilbao"],
  Netherlands: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"],
  Belgium: ["Brussels", "Antwerp", "Bruges", "Ghent", "Liege"],
  Switzerland: ["Zurich", "Geneva", "Basel", "Bern", "Lausanne"],
  Austria: ["Vienna", "Salzburg", "Graz", "Innsbruck", "Linz"],
  Sweden: ["Stockholm", "Gothenburg", "Malmo", "Uppsala", "Vasteras"],
  Norway: ["Oslo", "Bergen", "Trondheim", "Stavanger", "Tromso"],
  Denmark: ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg"],
  Finland: ["Helsinki", "Espoo", "Tampere", "Turku", "Oulu"],
  Ireland: ["Dublin", "Cork", "Galway", "Limerick", "Waterford"],
  Portugal: ["Lisbon", "Porto", "Braga", "Coimbra", "Faro"],
  Greece: ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa"],
  Poland: ["Warsaw", "Krakow", "Gdansk", "Wroclaw", "Poznan"],
  "Czech Republic": ["Prague", "Brno", "Ostrava", "Plzen", "Liberec"],
  Hungary: ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pecs"],
  Romania: ["Bucharest", "Cluj-Napoca", "Timisoara", "Iasi", "Brasov"],
  Bulgaria: ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse"],
  Croatia: ["Zagreb", "Split", "Dubrovnik", "Rijeka", "Zadar"],
  Serbia: ["Belgrade", "Novi Sad", "Nis", "Kragujevac", "Subotica"],
  Slovakia: ["Bratislava", "Kosice", "Presov", "Zilina", "Nitra"],
  Slovenia: ["Ljubljana", "Maribor", "Celje", "Kranj", "Koper"],
  Ukraine: ["Kyiv", "Lviv", "Odesa", "Kharkiv", "Dnipro"],
  Russia: ["Moscow", "Saint Petersburg", "Kazan", "Novosibirsk", "Sochi"],
  Turkey: ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya"],
  Japan: ["Tokyo", "Osaka", "Kyoto", "Yokohama", "Nagoya", "Sapporo"],
  China: [
    "Beijing",
    "Shanghai",
    "Guangzhou",
    "Shenzhen",
    "Chengdu",
    "Hong Kong",
  ],
  "South Korea": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon"],
  "North Korea": ["Pyongyang", "Hamhung", "Chongjin", "Nampo", "Sinuiju"],
  Thailand: ["Bangkok", "Chiang Mai", "Phuket", "Pattaya", "Krabi"],
  Singapore: ["Singapore"],
  Malaysia: [
    "Kuala Lumpur",
    "George Town",
    "Johor Bahru",
    "Ipoh",
    "Kota Kinabalu",
  ],
  Indonesia: ["Jakarta", "Bali", "Surabaya", "Bandung", "Yogyakarta"],
  Philippines: ["Manila", "Cebu", "Davao", "Quezon City", "Makati"],
  Vietnam: ["Hanoi", "Ho Chi Minh City", "Da Nang", "Hue", "Hai Phong"],
  Cambodia: [
    "Phnom Penh",
    "Siem Reap",
    "Sihanoukville",
    "Battambang",
    "Kampot",
  ],
  Laos: ["Vientiane", "Luang Prabang", "Pakse", "Savannakhet", "Thakhek"],
  Myanmar: ["Yangon", "Mandalay", "Naypyidaw", "Bagan", "Mawlamyine"],
  Nepal: ["Kathmandu", "Pokhara", "Lalitpur", "Bhaktapur", "Biratnagar"],
  Bhutan: ["Thimphu", "Paro", "Punakha", "Phuntsholing", "Trongsa"],
  Bangladesh: ["Dhaka", "Chittagong", "Khulna", "Sylhet", "Rajshahi"],
  "Sri Lanka": ["Colombo", "Kandy", "Galle", "Jaffna", "Negombo"],
  Pakistan: ["Karachi", "Lahore", "Islamabad", "Rawalpindi", "Peshawar"],
  Afghanistan: ["Kabul", "Kandahar", "Herat", "Mazar-i-Sharif", "Jalalabad"],
  Iran: ["Tehran", "Isfahan", "Shiraz", "Mashhad", "Tabriz"],
  Iraq: ["Baghdad", "Basra", "Mosul", "Erbil", "Najaf"],
  "Saudi Arabia": ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam"],
  "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Al Ain"],
  Qatar: ["Doha", "Al Rayyan", "Al Wakrah", "Umm Salal", "Lusail"],
  Kuwait: ["Kuwait City", "Al Ahmadi", "Hawalli", "Farwaniya", "Salmiya"],
  Oman: ["Muscat", "Salalah", "Sohar", "Nizwa", "Sur"],
  Bahrain: ["Manama", "Muharraq", "Riffa", "Isa Town", "Sitra"],
  Yemen: ["Sanaa", "Aden", "Taiz", "Hodeidah", "Mukalla"],
  Israel: ["Jerusalem", "Tel Aviv", "Haifa", "Eilat", "Nazareth"],
  Jordan: ["Amman", "Aqaba", "Irbid", "Zarqa", "Madaba"],
  Lebanon: ["Beirut", "Tripoli", "Sidon", "Tyre", "Byblos"],
  Syria: ["Damascus", "Aleppo", "Homs", "Latakia", "Hama"],
  Egypt: ["Cairo", "Alexandria", "Giza", "Luxor", "Sharm El Sheikh"],
  Libya: ["Tripoli", "Benghazi", "Misrata", "Sabha", "Zawiya"],
  Tunisia: ["Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte"],
  Algeria: ["Algiers", "Oran", "Constantine", "Annaba", "Blida"],
  Morocco: ["Casablanca", "Marrakesh", "Rabat", "Fes", "Tangier"],
  "South Africa": [
    "Johannesburg",
    "Cape Town",
    "Durban",
    "Pretoria",
    "Port Elizabeth",
  ],
  Nigeria: ["Lagos", "Abuja", "Kano", "Ibadan", "Port Harcourt"],
  Kenya: ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret"],
  Ethiopia: ["Addis Ababa", "Dire Dawa", "Mekelle", "Gondar", "Bahir Dar"],
  Ghana: ["Accra", "Kumasi", "Tamale", "Takoradi", "Cape Coast"],
  Uganda: ["Kampala", "Entebbe", "Jinja", "Gulu", "Mbarara"],
  Tanzania: ["Dar es Salaam", "Dodoma", "Arusha", "Mwanza", "Zanzibar City"],
  Zimbabwe: ["Harare", "Bulawayo", "Mutare", "Gweru", "Masvingo"],
  Zambia: ["Lusaka", "Ndola", "Kitwe", "Livingstone", "Kabwe"],
  Botswana: ["Gaborone", "Francistown", "Maun", "Kasane", "Selebi-Phikwe"],
  Namibia: ["Windhoek", "Swakopmund", "Walvis Bay", "Oshakati", "Luderitz"],
  Mozambique: ["Maputo", "Beira", "Nampula", "Quelimane", "Tete"],
  Angola: ["Luanda", "Benguela", "Huambo", "Lubango", "Malanje"],
  Cameroon: ["Yaounde", "Douala", "Bamenda", "Garoua", "Bafoussam"],
  Sudan: ["Khartoum", "Omdurman", "Port Sudan", "Kassala", "Nyala"],
  Argentina: ["Buenos Aires", "Cordoba", "Rosario", "Mendoza", "La Plata"],
  Brazil: ["Sao Paulo", "Rio de Janeiro", "Brasilia", "Salvador", "Fortaleza"],
  Chile: ["Santiago", "Valparaiso", "Concepcion", "La Serena", "Antofagasta"],
  Colombia: ["Bogota", "Medellin", "Cali", "Cartagena", "Barranquilla"],
  Peru: ["Lima", "Cusco", "Arequipa", "Trujillo", "Piura"],
  Venezuela: ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Merida"],
  Uruguay: [
    "Montevideo",
    "Punta del Este",
    "Salto",
    "Paysandu",
    "Colonia del Sacramento",
  ],
  Paraguay: [
    "Asuncion",
    "Ciudad del Este",
    "Encarnacion",
    "Luque",
    "San Lorenzo",
  ],
  Bolivia: ["La Paz", "Santa Cruz", "Cochabamba", "Sucre", "Oruro"],
  Ecuador: ["Quito", "Guayaquil", "Cuenca", "Loja", "Manta"],
  Mexico: ["Mexico City", "Guadalajara", "Monterrey", "Cancun", "Puebla"],
  Cuba: ["Havana", "Santiago de Cuba", "Varadero", "Camaguey", "Trinidad"],
  "Dominican Republic": [
    "Santo Domingo",
    "Santiago",
    "Punta Cana",
    "La Romana",
    "Puerto Plata",
  ],
  Jamaica: ["Kingston", "Montego Bay", "Negril", "Ocho Rios", "Spanish Town"],
  "Costa Rica": ["San Jose", "Liberia", "Limon", "Cartago", "Alajuela"],
  Panama: ["Panama City", "Colon", "David", "Santiago", "Chitre"],
  Guatemala: [
    "Guatemala City",
    "Antigua",
    "Quetzaltenango",
    "Escuintla",
    "Flores",
  ],
  Honduras: [
    "Tegucigalpa",
    "San Pedro Sula",
    "La Ceiba",
    "Choloma",
    "Comayagua",
  ],
  "El Salvador": [
    "San Salvador",
    "Santa Ana",
    "San Miguel",
    "Soyapango",
    "La Libertad",
  ],
  Nicaragua: ["Managua", "Granada", "Leon", "Masaya", "Esteli"],
  "New Zealand": [
    "Auckland",
    "Wellington",
    "Christchurch",
    "Hamilton",
    "Queenstown",
  ],
};

function loadCountries() {
  const countrySelect = $("#country");

  countrySelect.html('<option value="">-- Select Country --</option>');

  countries.forEach((country) => {
    const option = document.createElement("option");
    option.value = country;
    option.textContent = country;
    countrySelect.append(option);
  });
}

function loadCities() {
  const country = $("#country").val();
  console.log("Selected country:", country);
  const citySelect = $("#city");

  citySelect.html('<option value="">-- Select City --</option>');

  if (!country) return;

  const cities = countryCities[country] || [];

  cities.forEach((city) => {
    const option = document.createElement("option");
    option.value = city;
    option.textContent = city;
    citySelect.append(option);
  });
}

$(document).ready(function() {
  loadCountries();

  $("#country").on("change", loadCities);
});
